[package]
name = "Movemate"
version = "1.0.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
Std = "0x1"
AptosFramework = "0x1"
Econia = "0xc0deb00c"
Movemate = "0xb2207be128ba3dd1de79c064495a7c97642a513d33d4313e686c33896a332f1a"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"

[dependencies.Econia]
git = "https://github.com/econia-labs/econia.git"
subdir = "src/move/econia"
rev = "6a389ee8fd80ccd628ecbd994777113119ef0904"
